# Generated by Django 5.2.10 on 2026-02-25 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='media_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publication',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='technologies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('work_experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('technical_skills', models.JSONField(blank=True, default=list)),
                ('soft_skills', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('testimonials', models.JSONField(blank=True, default=list)),
                ('professional_philosophy', models.TextField(blank=True)),
                ('career_objectives', models.TextField(blank=True)),
                ('hobbies', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
