# Generated by Django 5.2.10 on 2026-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_media_links_publication_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
